# permissions for end users to edit inspectionpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: inspection-operator
    app.kubernetes.io/managed-by: kustomize
  name: inspectionpolicy-editor-role
rules:
- apiGroups:
  - inspection.example.com
  resources:
  - inspectionpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inspection.example.com
  resources:
  - inspectionpolicies/status
  verbs:
  - get
