apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: {{ .Release.Name }}
